__version__ = "2025.11.01"

from .nodes.character_prompt_node import (
    NODE_CLASS_MAPPINGS as CHARACTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.photo_aspect_extractor_node import (
    NODE_CLASS_MAPPINGS as PHOTO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PHOTO_DISPLAY_NAME_MAPPINGS,
)
from .nodes.character_edit_node import (
    NODE_CLASS_MAPPINGS as EDIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EDIT_DISPLAY_NAME_MAPPINGS,
)
from .nodes.background_edit_node import (
    NODE_CLASS_MAPPINGS as BG_EDIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BG_EDIT_DISPLAY_NAME_MAPPINGS,
)
from .nodes.background_generator_node import (
    NODE_CLASS_MAPPINGS as BG_GENERATOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BG_GENERATOR_DISPLAY_NAME_MAPPINGS,
)
from .nodes.prompt_combiner_node import (
    NODE_CLASS_MAPPINGS as COMBINER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMBINER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.lora_dataset_node import (
    NODE_CLASS_MAPPINGS as LORA_DATASET_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_DATASET_DISPLAY_NAME_MAPPINGS,
)
from .nodes.lora_train_node import (
    NODE_CLASS_MAPPINGS as LORA_TRAIN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_TRAIN_DISPLAY_NAME_MAPPINGS,
)
from .nodes.lora_validate_node import (
    NODE_CLASS_MAPPINGS as LORA_VALIDATE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_VALIDATE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.lora_dataset_validator_node import (
    NODE_CLASS_MAPPINGS as LORA_VALIDATOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_VALIDATOR_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **CHARACTER_NODE_CLASS_MAPPINGS,
    **PHOTO_NODE_CLASS_MAPPINGS,
    **EDIT_NODE_CLASS_MAPPINGS,
    **BG_EDIT_NODE_CLASS_MAPPINGS,
    **BG_GENERATOR_NODE_CLASS_MAPPINGS,
    **COMBINER_NODE_CLASS_MAPPINGS,
    **LORA_DATASET_NODE_CLASS_MAPPINGS,
    **LORA_TRAIN_NODE_CLASS_MAPPINGS,
    **LORA_VALIDATE_NODE_CLASS_MAPPINGS,
    **LORA_VALIDATOR_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CHARACTER_DISPLAY_NAME_MAPPINGS,
    **PHOTO_DISPLAY_NAME_MAPPINGS,
    **EDIT_DISPLAY_NAME_MAPPINGS,
    **BG_EDIT_DISPLAY_NAME_MAPPINGS,
    **BG_GENERATOR_DISPLAY_NAME_MAPPINGS,
    **COMBINER_DISPLAY_NAME_MAPPINGS,
    **LORA_DATASET_DISPLAY_NAME_MAPPINGS,
    **LORA_TRAIN_DISPLAY_NAME_MAPPINGS,
    **LORA_VALIDATE_DISPLAY_NAME_MAPPINGS,
    **LORA_VALIDATOR_DISPLAY_NAME_MAPPINGS,
}
