from .nodes.character_prompt_node import (
    NODE_CLASS_MAPPINGS as CHARACTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.fantasy_scene_node import (
    NODE_CLASS_MAPPINGS as FANTASY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FANTASY_DISPLAY_NAME_MAPPINGS,
)
from .nodes.photo_aspect_extractor_node import (
    NODE_CLASS_MAPPINGS as PHOTO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PHOTO_DISPLAY_NAME_MAPPINGS,
)
from .nodes.fashion_supermodel_node import (
    NODE_CLASS_MAPPINGS as FASHION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FASHION_DISPLAY_NAME_MAPPINGS,
)
from .nodes.upcycled_fashion_node import (
    NODE_CLASS_MAPPINGS as UPCYCLED_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UPCYCLED_DISPLAY_NAME_MAPPINGS,
)
from .nodes.character_edit_node import (
    NODE_CLASS_MAPPINGS as EDIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EDIT_DISPLAY_NAME_MAPPINGS,
)
from .nodes.prompt_combiner_node import (
    NODE_CLASS_MAPPINGS as COMBINER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMBINER_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **CHARACTER_NODE_CLASS_MAPPINGS,
    **FANTASY_NODE_CLASS_MAPPINGS,
    **PHOTO_NODE_CLASS_MAPPINGS,
    **FASHION_NODE_CLASS_MAPPINGS,
    **UPCYCLED_NODE_CLASS_MAPPINGS,
    **EDIT_NODE_CLASS_MAPPINGS,
    **COMBINER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CHARACTER_DISPLAY_NAME_MAPPINGS,
    **FANTASY_DISPLAY_NAME_MAPPINGS,
    **PHOTO_DISPLAY_NAME_MAPPINGS,
    **FASHION_DISPLAY_NAME_MAPPINGS,
    **UPCYCLED_DISPLAY_NAME_MAPPINGS,
    **EDIT_DISPLAY_NAME_MAPPINGS,
    **COMBINER_DISPLAY_NAME_MAPPINGS,
}
